# Generated by Django 3.2.4 on 2021-06-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
